<?php

return [
    /** 商品説明内のタイトルタグ */
    'AUCTION_TITLE' => '<u style="text-align: center; color: rgb(0, 0, 255);"><font size="5">%s</font></u>',

    /** 商品説明内の送料区分 */
    'AUCTION_SHIP_GROUP' => '<p>送料区分は%sです。</p>',

    /** 配送関係B～F定型文 */
    'SHIP_TEMPLATE' => '<table width="796" border="0" cellspacing="0" cellpadding="0" style="color: rgb(51, 51, 51); font-family: "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", メイリオ, Meiryo, "ＭＳ Ｐゴシック", "MS UI Gothic", Helvetica, Arial, sans-serif;"><tbody><tr height="22"><td width="652" height="22" colspan="9"><span style="font-weight: 700;"><u><font size="4">こちらの商品は、梱包サイズ3辺の合計が130cm以上 または 20kg以上 のため</font></u></span></td><td width="72"></td><td width="72"></td></tr><tr height="22"><td height="22" colspan="6"><span style="font-weight: 700;"><u><font size="4"><font color="#ff0000">個人宅様</font>までのお届けが出来ない商品となります。 </font></u></span></td><td></td><td></td><td></td><td></td><td></td></tr><tr height="22"><td height="22" colspan="11"><span style="font-weight: 700;"><u><font size="4">お近くの支店止め、もしくはお店や会社の住所等、屋号のある住所はお届け可能となります。</font></u></span></td></tr><tr height="22"><td height="22" colspan="6"><span style="font-weight: 700;"><u><font size="4">ご不便をおかけしますが何卒ご了承ください。 </font></u></span></td></tr></tbody></table>',

    /** 配送関係　ネコポス */
    'SHIP_NEKOPOS' => '<div class="note-editable card-block" contenteditable="true" role="textbox" aria-multiline="true" spellcheck="true" autocorrect="true"><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;"><div style="margin: 0px; padding: 0px;"><font color="#000000">別途ネコポス対応可能です。<br>(ポストまでのお届けになります)</font><font color="#000000">保障なしです。</font><font color="#000000">ネコポスをご希望の場合は、オーダーフォームへご記入をお願いいたします。</font><br></div><div><font color="#000000"><br></font></div></div></div>',

    /** 商品説明 */
    'PART_DISCRIPT' => '<div class="note-editable card-block" contenteditable="true" role="textbox" aria-multiline="true" spellcheck="true" autocorrect="true"><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;"><div style="margin: 0px; padding: 0px;">年式： %s年%s月&nbsp;</div><div style="margin: 0px; padding: 0px;"><br></div><div style="margin: 0px; padding: 0px;">車名：%s</div><div style="margin: 0px; padding: 0px;"><br></div><div style="margin: 0px; padding: 0px;">型式： %s</div><div style="margin: 0px; padding: 0px;"><br></div><div style="margin: 0px; padding: 0px;">グレード： %s</div></div><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;"><br></div><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">カラーNo： %s</div><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;"><br></div><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">トリムNo： %s</div><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;"><br></div><div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">走行距離：%s</div></div>',

    /** タイヤ前タグ */
    'WHEEL_BEFORE' => '<div class="note-editable card-block" contenteditable="true" role="textbox" aria-multiline="true" spellcheck="true" autocorrect="true" style="height: 180px;">',
    /** タイヤ商品説明 */
    'TIRE_DISCRIPT' => '<div style="margin: 0px; padding: 0px; font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">タイヤ &nbsp;&nbsp;%s/%sR%s&nbsp;%smm</div><div style="margin: 0px; padding: 0px; font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">タイヤメーカー %s</div><div style="margin: 0px; padding: 0px; font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">タイヤ製造年 %s年</div></div>',

    /** ホイール商品説明 */
    'WHEEL_DISCRIPT' => '<div style="margin: 0px; padding: 0px; color: rgb(51, 51, 51);"><div style="margin: 0px; padding: 0px; font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">ホイール &nbsp;%sＸ%sＪ&nbsp;&nbsp;&nbsp;&nbsp;OFF%s&nbsp;&nbsp;&nbsp;&nbsp;ＰＣＤ%s&nbsp;&nbsp;&nbsp;&nbsp;%s穴</div><div style="margin: 0px; padding: 0px; font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">ハブ径 &nbsp;&nbsp;約%sｍｍ&nbsp;&nbsp;&nbsp;%s本&nbsp;&nbsp;%s</div><div style="margin: 0px; padding: 0px; font-family: &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS UI Gothic&quot;, Helvetica, Arial, sans-serif; font-size: medium;">メーカー &nbsp;%s</div><br></div>',

    /** タイヤあとタグ */
    'WHEEl_END' => '</div>',
];